<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJhY1USy\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJhY1USy/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJhY1USy.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJhY1USy\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJhY1USy\appAppKernelProdContainer([
    'container.build_hash' => 'JhY1USy',
    'container.build_id' => 'e7b2ee1f',
    'container.build_time' => 1745850009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJhY1USy');
